-- 5월 식품들의 총매출 조회하기
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, A.PRICE * SUM(B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A, FOOD_ORDER B 
WHERE DATE_FORMAT(B.PRODUCE_DATE, "%Y-%m") = "2022-05" AND A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY B.PRODUCT_ID ORDER BY TOTAL_SALES DESC, A.PRODUCT_NAME;