-- 입양 시각 구하기(2)
WITH RECURSIVE TIME AS (
    SELECT 0 AS H
    UNION ALL
    SELECT H+1 FROM TIME WHERE H < 23)
    
SELECT H, COUNT(DATETIME) 
FROM TIME
    LEFT JOIN ANIMAL_OUTS ON H = HOUR(DATETIME)
GROUP BY H
ORDER BY H;