-- 조건에 부합하는 중고거래 상태 조회하기
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE,
IF(STATUS = 'SALE', '판매중', IF(STATUS = 'DONE', '거래완료', '예약중')) AS STATUS
FROM USED_GOODS_BOARD WHERE CREATED_DATE = '2022-10-05' ORDER BY 1 DESC