-- 조건에 맞는 도서와 저자 리스트 출력하기
SELECT A.BOOK_ID, B.AUTHOR_NAME, DATE_FORMAT(A.PUBLISHED_DATE, "%Y-%m-%d") AS DATE
FROM BOOK A, AUTHOR B WHERE A.AUTHOR_ID = B.AUTHOR_ID AND A.CATEGORY = '경제'
ORDER BY A.PUBLISHED_DATE;