-- 조건에 맞는 사용자 정보 조회하기
SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL FROM USED_GOODS_BOARD A
JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY A.WRITER_ID HAVING TOTAL >= 700000
ORDER BY 3