-- 카테고리 별 도서 판매량 집계하기
SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES FROM BOOK A, BOOK_SALES B
WHERE A.BOOK_ID = B.BOOK_ID AND DATE_FORMAT(B.SALES_DATE, "%Y-%m") = '2022-01'
GROUP BY A.CATEGORY ORDER BY A.CATEGORY