-- 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE*30*(100-B.DISCOUNT_RATE)/100) FEE
FROM CAR_RENTAL_COMPANY_CAR A ,
(SELECT CAR_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상') B
WHERE A.CAR_TYPE = B.CAR_TYPE AND
A.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE END_DATE > '2022-11-00' AND START_DATE < '2022-12-00')
AND A.CAR_TYPE IN ('세단', 'SUV') -- AND A.DAILY_FEE*30*(100-B.DISCOUNT_RATE)/100 BETWEEN 500000 AND 2000000
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC